<?php

/* ------------------------------------------------------------------------- *
 *  LOAD AND REGISTER GALLERY MODULE
/* ------------------------------------------------------------------------- */
//Fired in add_action( 'after_setup_theme', 'sek_register_modules', 50 );
function sek_get_module_params_for_czr_gallery_module() {
    return array(
        'dynamic_registration' => true,
        'module_type' => 'czr_gallery_module',
        'is_father' => true,
        'children' => array(
            'gallery_collec' => 'czr_gallery_collection_child',
            'gallery_opts' => 'czr_gallery_opts_child'
        ),
        'name' => __('Gallery', 'text_doma'),
        'starting_value' => array(
            'gallery_collec' => array(
                array( 'img' =>  NIMBLE_BASE_URL . '/assets/img/default-img.png' ),
                array( 'img' =>  NIMBLE_BASE_URL . '/assets/img/default-img.png' ),
                array( 'img' =>  NIMBLE_BASE_URL . '/assets/img/default-img.png' )
            )
        ),
        'sanitize_callback' => '\Nimble\sanitize_cb__czr_gallery_module',
        // 'validate_callback' => 'function_prefix_to_be_replaced_validate_callback__czr_social_module',
        'css_selectors' => array( '.sek-gal-wrapper' ),//array( '.sek-icon i' ),
        'render_tmpl_path' => "gallery_tmpl.php",
        // 'front_assets' => array(
        //       'czr-font-awesome' => array(
        //           'type' => 'css',
        //           //'handle' => 'czr-font-awesome',
        //           'src' => NIMBLE_BASE_URL . '/assets/front/fonts/css/fontawesome-all.min.css'
        //           //'deps' => array()
        //       )
        // )
    );
}

/* ------------------------------------------------------------------------- *
 *  SANITIZATION
/* ------------------------------------------------------------------------- */
// convert into a json to prevent emoji breaking global json data structure
// fix for https://github.com/presscustomizr/nimble-builder/issues/544
function sanitize_cb__czr_gallery_module( $value ) {
    if ( !is_array( $value ) )
        return $value;
    if ( !empty($value['gallery_collec']) && is_array( $value['gallery_collec'] ) ) {
        foreach( $value['gallery_collec'] as $key => $data ) {
            if ( array_key_exists( 'caption_text', $data ) && is_string( $data['caption_text'] ) ) {
                $value['gallery_collec'][$key]['caption_text'] = sek_maybe_encode_richtext( $data['caption_text'] );
            }
            if ( array_key_exists( 'title_text', $data ) && is_string( $data['title_text'] ) ) {
                $value['gallery_collec'][$key]['title_text'] = sek_maybe_encode_richtext( $data['title_text'] );
            }
        }
    }
    return $value;
}

/* ------------------------------------------------------------------------- *
 *  MAIN SETTINGS
/* ------------------------------------------------------------------------- */
function sek_get_module_params_for_czr_gallery_collection_child() {
    return array(
        'dynamic_registration' => true,
        'module_type' => 'czr_gallery_collection_child',
        'is_crud' => true,
        'name' => sprintf('<i class="material-icons" style="font-size: 1.2em;">toc</i> %1$s', __( 'Image collection', 'text_doma' ) ),
        // 'starting_value' => array(
        //     'caption_text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.'
        // ),
        //'sanitize_callback' => '\Nimble\sanitize_callback__czr_simple_form_module',
        //'css_selectors' => array( '.sek-social-icon' ),//array( '.sek-icon i' ),
        'tmpl' => array(
            'pre-item' => array(
                // 'page-id' => array(
                //     'input_type'  => 'content_picker',
                //     'title'       => __('Pick a page', 'text_doma')
                // ),
                'img' => array(
                    'input_type'  => 'upload',
                    'title'       => __('Pick an image', 'text_doma'),
                    'default'     => ''
                ),
            ),
            'item-inputs' => array(
                'img' => array(
                    'input_type'  => 'upload',
                    'title'       => __('Pick an image', 'text_doma'),
                    'default'     => ''
                ),
                // 'img-size' => array(
                //     'input_type'  => 'simpleselect',
                //     'title'       => __('Select the image size', 'text_doma'),
                //     'default'     => 'large',
                //     'choices'     => sek_get_select_options_for_input_id( 'img-size' ),
                //     'notice_before' => __('Select a size for this image among those generated by WordPress.', 'text_doma' )
                // ),





                // 'link-to' => array(
                //     'input_type'  => 'simpleselect',
                //     'title'       => __('Schedule an action on click or tap', 'text_doma'),
                //     'default'     => 'no-link',
                //     'choices'     => array(
                //         'no-link' => __('No click action', 'text_doma' ),
                //         'img-lightbox' =>__('Lightbox : enlarge the image, and dim out the rest of the content', 'text_doma' ),
                //         'url' => __('Link to site content or custom url', 'text_doma' ),
                //         'img-file' => __('Link to image file', 'text_doma' ),
                //         'img-page' =>__('Link to image page', 'text_doma' )
                //     ),
                //     'title_width' => 'width-100',
                //     'width-100'   => true,
                //     'notice_after' => __('Note that some click actions are disabled during customization.', 'text_doma' ),
                // ),
                // 'link-pick-url' => array(
                //     'input_type'  => 'content_picker',
                //     'title'       => __('Link url', 'text_doma'),
                //     'default'     => array()
                // ),
                // 'link-custom-url' => array(
                //     'input_type'  => 'text',
                //     'title'       => __('Custom link url', 'text_doma'),
                //     'default'     => ''
                // ),
                // 'link-target' => array(
                //     'input_type'  => 'nimblecheck',
                //     'title'       => __('Open link in a new page', 'text_doma'),
                //     'default'     => false,
                //     'title_width' => 'width-80',
                //     'input_width' => 'width-20',
                // ),




                // 'h_alignment_css' => array(
                //     'input_type'  => 'horizAlignmentWithDeviceSwitcher',
                //     'title'       => __('Alignment', 'text_doma'),
                //     'default'     => array( 'desktop' => 'center' ),
                //     'refresh_markup' => false,
                //     'refresh_stylesheet' => true,
                //     'css_identifier' => 'h_alignment',
                //     'title_width' => 'width-100',
                //     'width-100'   => true,
                //     'css_selectors'=> 'figure'
                // ),
                // 'use_custom_title_attr' => array(
                //     'input_type'  => 'nimblecheck',
                //     'title'       => __('Set the text displayed when the mouse is held over', 'text_doma'),
                //     'default'     => false,
                //     'title_width' => 'width-80',
                //     'input_width' => 'width-20',
                //     'notice_after' => __('If not specified, Nimble will use by order of priority the caption, the description, and the image title. Those properties can be edited for each image in the media library.')
                // ),
                // 'heading_title' => array(
                //     'input_type'         => 'text',
                //     'title' => __('Custom text displayed on mouse hover', 'text_domain_to' ),
                //     'default'            => '',
                //     'title_width' => 'width-100',
                //     'width-100'         => true
                // ),
                // 'use_custom_width' => array(
                //     'input_type'  => 'nimblecheck',
                //     'title'       => __( 'Custom image width', 'text_doma' ),
                //     'default'     => 0,
                //     'refresh_stylesheet' => true,
                //     'html_before' => '<hr/>'
                // ),
                // 'custom_width' => array(
                //     'input_type'  => 'range_with_unit_picker_device_switcher',
                //     'title'       => __('Width', 'text_doma'),
                //     'min' => 1,
                //     'max' => 100,
                //     //'unit' => '%',
                //     'default'     => array( 'desktop' => '100%' ),
                //     'max'     => 500,
                //     'width-100'   => true,
                //     'title_width' => 'width-100',
                //     'refresh_markup' => false,
                //     'refresh_stylesheet' => true
                // ),
                // 'use_custom_height' => array(
                //     'input_type'  => 'nimblecheck',
                //     'title'       => __( 'Custom image max height', 'text_doma' ),
                //     'default'     => 0,
                //     'refresh_stylesheet' => true
                // ),
                // 'custom_height' => array(
                //     'input_type'  => 'range_with_unit_picker_device_switcher',
                //     'title'       => __('Height', 'text_doma'),
                //     'min' => 1,
                //     'max' => 100,
                //     //'unit' => '%',
                //     'default'     => array( 'desktop' => '100%' ),
                //     'max'     => 500,
                //     'width-100'   => true,
                //     'title_width' => 'width-100',
                //     'refresh_markup' => false,
                //     'refresh_stylesheet' => true
                // ),
                // 'use_box_shadow' => array(
                //     'input_type'  => 'nimblecheck',
                //     'title'       => __( 'Apply a shadow', 'text_doma' ),
                //     'default'     => 0,
                //     'html_before' => '<hr/>'
                // ),
                // 'img_hover_effect' => array(
                //     'input_type'  => 'simpleselect',
                //     'title'       => __('Mouse over effect', 'text_doma'),
                //     'default'     => 'none',
                //     'choices'     => sek_get_select_options_for_input_id( 'img_hover_effect' ),
                //     'html_after' => $pro_text
                // )
            )//'item-inputs'
        ),
        'render_tmpl_path' => '',
    );
}


/* ------------------------------------------------------------------------- *
 *  GALLERY OPTIONS
/* ------------------------------------------------------------------------- */
function sek_get_module_params_for_czr_gallery_opts_child() {
    $title_content_selector = array( '.sek-accord-item .sek-accord-title *' );
    $main_content_selector = array( '.sek-accord-item .sek-accord-content', '.sek-accord-item .sek-accord-content *' );
    return array(
        'dynamic_registration' => true,
        'module_type' => 'czr_gallery_opts_child',
        'name' => sprintf('<i class="material-icons" style="font-size: 1.2em;">tune</i> %1$s', __( 'Gallery options', 'text_doma' ) ),
        //'sanitize_callback' => '\Nimble\sanitize_callback__czr_simple_form_module',
        // 'starting_value' => array(
        //     'button_text' => __('Click me','text_doma'),
        //     'color_css'  => '#ffffff',
        //     'bg_color_css' => '#020202',
        //     'bg_color_hover' => '#151515', //lighten 15%,
        //     'use_custom_bg_color_on_hover' => 0,
        //     'border_radius_css' => '2',
        //     'h_alignment_css' => 'center',
        //     'use_box_shadow' => 1,
        //     'push_effect' => 1
        // ),
        //'css_selectors' => array( '.sek-social-icons-wrapper' ),//array( '.sek-icon i' ),
        'tmpl' => array(
            'item-inputs' => array(
                // 'layout'  => array(
                //     'input_type'  => 'simpleselect',
                //     'title'       => __( 'Grid layout : list or grid', 'text_doma' ),
                //     'default'     => 'list',
                //     'width-100'   => true,
                //     'title_width' => 'width-100',
                //     'choices'     => [],
                //     //'html_before' => '<hr>',
                //     'refresh_stylesheet' => true, //<= some CSS rules are layout dependant
                //     //'html_before' => $pro_text
                // ),//null,
                'columns'  => array(
                    'input_type'  => 'range_simple_device_switcher',
                    'title'       => __( 'Number of columns', 'text_doma' ),
                    'default'     => array( 'desktop' => '2', 'tablet' => '2', 'mobile' => '1' ),
                    'min'         => 1,
                    'max'         => 12,
                    'step'        => 1,
                    'width-100'   => true,
                    'title_width' => 'width-100',
                    'refresh_stylesheet' => true //<= some CSS rules are layout dependant
                ),//null,
                'column_gap'  => array(
                    'input_type'  => 'range_with_unit_picker_device_switcher',
                    'title'       => __( 'Space between columns', 'text_doma' ),
                    'min' => 0,
                    'max' => 100,
                    'default'     => array( 'desktop' => '20px' ),
                    'width-100'   => true,
                    'title_width' => 'width-100',
                    'refresh_markup' => false,
                    'refresh_stylesheet' => true
                ),//null,

                'row_gap'  => array(
                    'input_type'  => 'range_with_unit_picker_device_switcher',
                    'title'       => __( 'Space between rows', 'text_doma' ),
                    'min' => 0,
                    'max' => 100,
                    'default'     => array( 'desktop' => '25px' ),
                    'width-100'   => true,
                    'title_width' => 'width-100',
                    'refresh_markup' => false,
                    'refresh_stylesheet' => true
                ),//null,

                'img-size' => array(
                    'input_type'  => 'simpleselect',
                    'title'       => __('Select the image size', 'text_doma'),
                    'default'     => 'large',
                    'choices'     => sek_get_select_options_for_input_id( 'img-size' ),
                    'notice_before' => __('Select a size for this image among those generated by WordPress.', 'text_doma' )
                ),
            )
        ),
        'render_tmpl_path' => '',
    );
}




/* ------------------------------------------------------------------------- *
 *  SCHEDULE CSS RULES FILTERING
/* ------------------------------------------------------------------------- */
// PER ITEM CSS DESIGN => FILTERING OF EACH ITEM MODEL, TARGETING THE ID ( [data-sek-item-id="893af157d5e3"] )
//add_filter( 'sek_add_css_rules_for_single_item_in_module_type___czr_gallery_collection_child', '\Nimble\sek_add_css_rules_for_items_in_czr_gallery_collection_child', 10, 2 );

// filter documented in Sek_Dyn_CSS_Builder::sek_css_rules_sniffer_walker
// Note : $complete_modul_model has been normalized
// @return populated $rules
// @param $params
// Array
// (
//     [input_list] => Array
//         (
//             [icon] => fab fa-acquisitions-incorporated
//             [link] => https://twitter.com/home
//             [title_attr] => Follow me on twitter
//             [link_target] =>
//             [color_css] => #dd9933
//             [use_custom_color_on_hover] =>
//             [social_color_hover] => #dd3333
//             [id] => 62316ab99b4d
//         )
//     [parent_module_id] =>
//     [module_type] => czr_gallery_collection_child
//     [module_css_selector] => Array
//         (
//             [0] => .sek-social-icon
//         )

// )
function sek_add_css_rules_for_items_in_czr_gallery_collection_child( $rules, $params ) {
    // $item_input_list = wp_parse_args( $item_input_list, $default_value_model );
    $item_model = isset( $params['input_list'] ) ? $params['input_list'] : array();

    // VERTICAL ALIGNMENT
    // if ( !empty( $item_model[ 'v_alignment' ] ) ) {
    //     if ( !is_array( $item_model[ 'v_alignment' ] ) ) {
    //         sek_error_log( __FUNCTION__ . ' => error => the v_alignment option should be an array( {device} => {alignment} )');
    //     }
    //     $v_alignment_value = is_array( $item_model[ 'v_alignment' ] ) ? $item_model[ 'v_alignment' ] : array();
    //     $v_alignment_value = wp_parse_args( $v_alignment_value, array(
    //         'desktop' => 'center',
    //         'tablet' => '',
    //         'mobile' => ''
    //     ));
    //     $mapped_values = array();
    //     foreach ( $v_alignment_value as $device => $align_val ) {
    //         switch ( $align_val ) {
    //             case 'top' :
    //                 $mapped_values[$device] = "flex-start";
    //             break;
    //             case 'center' :
    //                 $mapped_values[$device] = "center";
    //             break;
    //             case 'bottom' :
    //                 $mapped_values[$device] = "flex-end";
    //             break;
    //         }
    //     }
    //     $rules = sek_set_mq_css_rules( array(
    //         'value' => $mapped_values,
    //         'css_property' => 'align-items',
    //         'selector' => sprintf( '[data-sek-id="%1$s"]  [data-sek-item-id="%2$s"] .sek-slider-text-wrapper', $params['parent_module_id'], $item_model['id'] )
    //     ), $rules );
    // }//Vertical alignment


    return $rules;
}




// GLOBAL CSS DESIGN => FILTERING OF THE ENTIRE MODULE MODEL
//add_filter( 'sek_add_css_rules_for_module_type___czr_gallery_module', '\Nimble\sek_add_css_rules_for_czr_gallery_module', 10, 2 );

// filter documented in Sek_Dyn_CSS_Builder::sek_css_rules_sniffer_walker
// Note : $complete_modul_model has been normalized
// @return populated $rules
function sek_add_css_rules_for_czr_gallery_module( $rules, $complete_modul_model ) {
    if ( empty( $complete_modul_model['value'] ) || !is_array( $complete_modul_model['value'] ) )
      return $rules;

    $value = $complete_modul_model['value'];
    $defaults = sek_get_default_module_model( 'czr_gallery_module');
    $gallery_defaults = $defaults['gallery_opts'];

    $gallery_opts = $value['gallery_opts'];

    //sek_error_log('sek_get_default_module_model() ?', sek_get_default_module_model( 'czr_gallery_module') );

    // TEXT COLOR ( for the plus / minus icon )
    if ( !empty( $gallery_opts[ 'color_css' ] ) && $gallery_defaults[ 'color_css' ] != $gallery_opts[ 'color_css' ] ) {
        $rules[] = array(
            'selector' => sprintf( '[data-sek-id="%1$s"] .sek-module-inner .sek-accord-wrapper .sek-accord-item .expander span', $complete_modul_model['id'] ),
            'css_rules' => 'background:'. $gallery_opts[ 'color_css' ] .';',
            'mq' =>null
        );
    }
    // ACTIVE / HOVER TEXT COLOR ( for the plus / minus icon )
    if ( !empty( $gallery_opts[ 'color_active_css' ] ) && $gallery_defaults[ 'color_active_css' ] != $gallery_opts[ 'color_active_css' ] ) {
        $rules[] = array(
            'selector' => sprintf( '[data-sek-id="%1$s"] .sek-module-inner .sek-accord-wrapper [data-sek-expanded="true"] .sek-accord-title .expander span, [data-sek-id="%1$s"] .sek-module-inner .sek-accord-wrapper .sek-accord-item .sek-accord-title:hover .expander span', $complete_modul_model['id'] ),
            'css_rules' => sprintf('background:%s;', $gallery_opts[ 'color_active_css' ] ),
            'mq' =>null
        );
    }

    return $rules;
}


?>